### ISSUE TITLE
Use Regex rather

### ISSUE THREAD

**Issue by yesitskev** [GoodGuyGroves/Discord-Pickup#2]
https://github.com/GoodGuyGroves/Discord-Pickup/blob/master/bot.js#L118-L119 should rather use regex for alpha numeric characters.

**Comment by GoodGuyGroves** [comment]
Should rather use regex? I'm not if I'm misunderstanding you or you're misunderstanding me. I actually want to implement a function that takes a value and converts it to one or two letters.

eg: 1 = A, 2 = B, 26 = Z, 27 = AA, 28 = AB, and so on.

**Comment by yesitskev** [comment]
Sorry I assumed instead of read the rest of the function. I think `String.charAt(..)` or something also exists, so you don't have to use an array.

I'm also assuming that the team name / type would be defined within the scope of the pickup thus rendering half the alphabet characters useless (that team won't exist?)

**Comment by GoodGuyGroves** [comment]
String.charAt() doesn't do what you think it does or what you think I want it to do. It doesn't really matter, most of that code is going to fall away anyway. :)

**Comment by yesitskev** [comment]
If it doesn't return a char at the index position specified of a string then lord have mercy.
